import Link from "next/link";
import { AutoklinikNavbar } from "@/components/autoklinik-navbar";
import { AutoklinikFooter } from "@/components/autoklinik-footer";

export const metadata = {
  title: "AGB für Werkstattleistungen | Autoklinik Reutlingen",
  description: "Allgemeine Geschäftsbedingungen für Reparatur-, Wartungs- und Diagnoseleistungen der Autoklinik Reutlingen GmbH.",
  alternates: { canonical: "https://autoklinik-reutlingen.de/agb" },
  robots: { index: false, follow: false },
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="border-t pt-8" style={{ borderColor: "#e4edf3" }}><h2 className="text-base font-bold mb-3" style={{ color: "#0d1b2a" }}>{title}</h2><div className="text-sm leading-relaxed flex flex-col gap-3" style={{ color: "#4a6070" }}>{children}</div></section>;
}

export default function AgbPage() {
  return (
    <>
      <AutoklinikNavbar />
      <main className="font-sans">
        <header className="py-16" style={{ backgroundColor: "#0d1b2a" }}><div className="max-w-3xl mx-auto px-6"><span className="inline-block text-xs font-semibold uppercase tracking-widest mb-4" style={{ color: "#4aadce" }}>Rechtliches</span><h1 className="text-4xl font-bold text-white text-balance mb-3">Allgemeine Geschäftsbedingungen</h1><p className="text-sm" style={{ color: "rgba(255,255,255,0.64)" }}>Für Reparatur-, Wartungs-, Diagnose- und sonstige Werkstattleistungen.</p></div></header>
        <section className="py-16" style={{ backgroundColor: "#f4f8fb" }}><div className="max-w-3xl mx-auto px-6"><div className="rounded-2xl p-8 flex flex-col gap-8" style={{ backgroundColor: "#fff", border: "1px solid #e4edf3" }}>
          <div><p className="text-sm leading-relaxed" style={{ color: "#4a6070" }}>Diese Allgemeinen Geschäftsbedingungen gelten für Verträge zwischen der <strong style={{ color: "#0d1b2a" }}>Autoklinik Reutlingen GmbH, Haldenhaustraße 3, 72770 Reutlingen</strong> und ihren Kundinnen und Kunden über Werkstattleistungen.</p><p className="mt-3 text-xs" style={{ color: "#8aa0ae" }}>Stand: September 2026</p></div>
          <Section title="1. Geltungsbereich und Vertragspartner"><p>Die AGB gelten für alle Reparatur-, Wartungs-, Inspektions-, Diagnose-, Prüf- und sonstigen Serviceaufträge, die mit der Autoklinik Reutlingen GmbH geschlossen werden. Entgegenstehende Bedingungen der Kundin oder des Kunden gelten nur, wenn wir ihrer Geltung ausdrücklich in Textform zustimmen.</p><p>Vertragspartner ist ausschließlich die Autoklinik Reutlingen GmbH. Ioannis Tsannis und die 741SVE Digitalagentur verwalten und entwickeln die Website als technische Dienstleister; sie sind nicht Vertragspartner für Werkstattaufträge.</p></Section>
          <Section title="2. Angebot und Auftragserteilung"><p>Ein Auftrag kommt durch unsere Annahme des Auftrags in Textform, telefonisch oder durch die tatsächliche Aufnahme der Arbeiten zustande. Der konkrete Leistungsumfang ergibt sich aus dem Auftrag, der Auftragsbestätigung oder der gemeinsamen Absprache.</p><p>Wir dürfen Aufträge ablehnen, wenn die Durchführung technisch, rechtlich oder wirtschaftlich nicht möglich oder nicht zumutbar ist.</p></Section>
          <Section title="3. Kostenvoranschlag und Zusatzarbeiten"><p>Kostenvoranschläge sind unverbindliche Schätzungen, sofern sie nicht ausdrücklich als verbindlich bezeichnet werden. Erkennbar notwendige Zusatzarbeiten stimmen wir vor ihrer Ausführung mit der Kundin oder dem Kunden ab.</p><p>Ist eine Rücksprache trotz zumutbarer Bemühungen nicht möglich und sind die Zusatzarbeiten zur Wiederherstellung der Verkehrs- oder Betriebssicherheit erforderlich, dürfen wir diese bis zu einem angemessenen Betrag ausführen. Übersteigt der voraussichtliche Gesamtpreis den vereinbarten oder mitgeteilten Rahmen wesentlich, informieren wir unverzüglich.</p></Section>
          <Section title="4. Fahrzeugübergabe und Verwahrung"><p>Das Fahrzeug ist zum vereinbarten Termin mit sämtlichen für den Auftrag erforderlichen Unterlagen und Schlüsseln zu übergeben. Persönliche Gegenstände sollten vor der Übergabe aus dem Fahrzeug entfernt werden.</p><p>Wir verwahren das Fahrzeug nur für die Dauer der Auftragsabwicklung und eine angemessene Abholfrist. Nach Fertigstellung informieren wir über die Abholung. Bei erheblicher Überschreitung der Abholfrist können angemessene Standkosten entstehen, sofern wir darauf hingewiesen haben.</p></Section>
          <Section title="5. Durchführung, Teile und Probefahrt"><p>Wir führen Arbeiten nach den anerkannten Regeln der Technik und, soweit vereinbart, nach Herstellervorgaben aus. Soweit nicht anders vereinbart, dürfen wir für die Reparatur geeignete Original-, Ident- oder qualitativ gleichwertige Ersatzteile verwenden.</p><p>Die Kundin oder der Kunde gestattet erforderliche Prüf- und Probefahrten. Umfang und Dauer werden auf das notwendige Maß beschränkt.</p></Section>
          <Section title="6. Abnahme und Abholung"><p>Nach Abschluss der Arbeiten wird das Fahrzeug zur Abholung bereitgestellt. Mit der Abholung oder der vorbehaltlosen Entgegennahme gilt die Leistung als abgenommen, sofern kein offensichtlicher Mangel gerügt wird. Festgestellte Beanstandungen sind möglichst konkret mitzuteilen.</p></Section>
          <Section title="7. Preise und Zahlung"><p>Es gelten die bei Auftragserteilung vereinbarten Preise oder, falls keine Vereinbarung getroffen wurde, unsere zum Zeitpunkt der Leistung gültigen Preise. Preise verstehen sich einschließlich der gesetzlichen Umsatzsteuer, sofern nicht anders ausgewiesen.</p><p>Rechnungen sind bei Abholung ohne Abzug zur Zahlung fällig. Bei Zahlungsverzug gelten die gesetzlichen Regelungen. Wir dürfen die Herausgabe des Fahrzeugs im Rahmen des gesetzlichen Unternehmerpfandrechts bis zur vollständigen Zahlung verweigern.</p></Section>
          <Section title="8. Mängelrechte"><p>Bei Mängeln der Werkstattleistung gelten die gesetzlichen Mängelrechte. Wir dürfen zunächst nach unserer Wahl nachbessern oder neu leisten. Die Kundin oder der Kunde hat uns hierfür Gelegenheit und Zugang zum Fahrzeug zu geben.</p><p>Bei sicherheitsrelevanten oder dringenden Mängeln ist die Autoklinik unverzüglich zu informieren. Eigenmächtige Reparaturversuche oder die Beauftragung Dritter können die Mängelrechte beeinträchtigen, soweit dadurch zusätzliche Kosten oder die Prüfung der Ursache erschwert werden.</p></Section>
          <Section title="9. Haftung"><p>Wir haften unbeschränkt für Vorsatz, grobe Fahrlässigkeit, Schäden aus der Verletzung von Leben, Körper oder Gesundheit sowie nach zwingenden gesetzlichen Vorschriften. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den vertragstypischen, vorhersehbaren Schaden begrenzt.</p><p>Im Übrigen ist die Haftung für leicht fahrlässige Pflichtverletzungen ausgeschlossen. Die Haftungsbeschränkungen gelten nicht, soweit eine Beschaffenheitsgarantie übernommen oder ein Mangel arglistig verschwiegen wurde.</p></Section>
          <Section title="10. Eigentum, Altteile und Entsorgung"><p>Ausgebaute Teile werden, sofern nicht bei Auftragserteilung anders vereinbart, von uns fachgerecht verwertet oder entsorgt. Die Herausgabe ausgebauter Teile kann vor der Entsorgung verlangt werden, sofern dem keine gesetzlichen oder technischen Gründe entgegenstehen.</p></Section>
          <Section title="11. Datenschutz"><p>Informationen zur Verarbeitung personenbezogener Daten finden Sie in unserer <Link href="/datenschutz" className="underline" style={{ color: "#0074a2" }}>Datenschutzerklärung</Link>.</p></Section>
          <Section title="12. Verbraucherrechte und Streitbeilegung"><p>Gesetzliche Verbraucherrechte bleiben unberührt. Wir nehmen nicht an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teil und sind hierzu nicht verpflichtet.</p></Section>
          <Section title="13. Schlussbestimmungen"><p>Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts, soweit dem keine zwingenden Verbraucherschutzvorschriften entgegenstehen. Für Verbraucherinnen und Verbraucher gelten die gesetzlichen Gerichtsstände. Sollte eine Bestimmung unwirksam sein, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt.</p></Section>
        </div><p className="mt-8 text-center text-xs" style={{ color: "#8aa0ae" }}><Link href="/datenschutz" className="hover:underline">Datenschutz</Link>{" · "}<Link href="/agb" className="hover:underline">AGB</Link>{" · "}<Link href="/impressum" className="hover:underline">Impressum</Link></p></div></section>
      </main><AutoklinikFooter />
    </>
  );
}
