import Link from "next/link";
import { AutoklinikNavbar } from "@/components/autoklinik-navbar";
import { AutoklinikFooter } from "@/components/autoklinik-footer";
import { ContactSection } from "@/components/contact-section";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { FaqSchema, ServiceSchema } from "@/components/structured-data";
import { SITE } from "@/lib/site-config";
import { autoaufbereitungExtras, autoaufbereitungFaqs, autoaufbereitungPackages, autoaufbereitungPricingNote } from "@/lib/autoaufbereitung-data";

const jsonLd = { "@context": "https://schema.org", "@type": "AutoRepair", name: SITE.name, telephone: SITE.phone.e164, address: { "@type": "PostalAddress", streetAddress: SITE.address.street, addressLocality: SITE.address.city, postalCode: SITE.address.zip, addressCountry: SITE.address.country } };

export default function AutoaufbereitungPage() {
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
    <ServiceSchema name="Autoaufbereitung Reutlingen" description="Professionelle Fahrzeugaufbereitung innen und außen in Reutlingen – transparente Pakete für Innenraumreinigung, Autopflege und Außenreinigung." url="/autoaufbereitung-reutlingen" />
    <FaqSchema items={autoaufbereitungFaqs.map((f) => ({ question: f.q, answer: f.a }))} />
    <AutoklinikNavbar />
    <main>
      <section className="pt-32 pb-20" style={{ backgroundColor: "#002e40" }}>
        <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16">
          <Breadcrumbs variant="dark" items={[{ name: "Startseite", url: "/" }, { name: "Autoaufbereitung", url: "/autoaufbereitung-reutlingen" }]} />
          <div className="max-w-4xl pt-10">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] mb-5" style={{ color: "#4db8d8" }}>Autopflege in Reutlingen</p>
            <h1 className="text-balance font-bold tracking-tight leading-[1.08] mb-6" style={{ color: "#fff", fontSize: "clamp(2.5rem, 6vw, 4.8rem)" }}>Professionelle Autoaufbereitung in Reutlingen – innen & außen</h1>
            <p className="max-w-2xl text-lg leading-relaxed mb-10" style={{ color: "rgba(255,255,255,0.76)" }}>Wir reinigen und pflegen Ihr Fahrzeug materialgerecht – vom gepflegten Innenraum bis zum sauberen Außenfinish. Transparente Paketpreise, faire Zuschläge und zusätzliche Kosten immer nach Absprache.</p>
            <div className="flex flex-wrap gap-3"><Link href="/terminbuchung" className="rounded-full px-7 py-3.5 text-sm font-semibold text-white" style={{ backgroundColor: "#0074a2" }}>Aufbereitung anfragen</Link><a href={SITE.phone.href} className="rounded-full border px-7 py-3.5 text-sm font-semibold" style={{ borderColor: "rgba(255,255,255,0.25)", color: "#fff" }}>{SITE.phone.display}</a></div>
          </div>
        </div>
      </section>

      <section className="py-20" style={{ backgroundColor: "#fff" }}><div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16"><p className="text-xs font-semibold uppercase tracking-[0.2em] mb-4" style={{ color: "#0074a2" }}>Pakete</p><h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-balance mb-4" style={{ color: "#002e40" }}>Die passende Fahrzeugaufbereitung auf einen Blick</h2><p className="max-w-2xl leading-relaxed mb-12" style={{ color: "#4a6272" }}>Innenraumreinigung und Außenreinigung lassen sich einzeln buchen. Für die komplette Autoaufbereitung ist das Kombipaket der stärkste Preisvorteil.</p><div className="grid gap-px sm:grid-cols-2 lg:grid-cols-3" style={{ backgroundColor: "#d5e8f0" }}>{autoaufbereitungPackages.map((pack) => <article key={pack.name} className={`p-7 relative ${pack.name === "Komplettaufbereitung" ? "lg:col-span-3" : ""}`} style={{ backgroundColor: pack.name === "Komplettaufbereitung" ? "#eaf6fa" : "#fff" }}>{pack.name === "Innenraum Premium" && <span className="absolute top-5 right-5 rounded-full px-3 py-1 text-[11px] font-bold uppercase tracking-wider" style={{ backgroundColor: "#0074a2", color: "#fff" }}>Beliebt</span>} {pack.name === "Komplettaufbereitung" && <span className="text-xs font-bold uppercase tracking-[0.18em]" style={{ color: "#0074a2" }}>Empfohlenes Gesamtpaket</span>}<div className="flex items-end justify-between gap-4 mb-3"><h3 className="text-xl font-bold" style={{ color: "#002e40" }}>{pack.name}</h3><strong className="text-3xl font-bold whitespace-nowrap" style={{ color: "#0074a2" }}>{pack.price}</strong></div><p className="text-sm leading-relaxed mb-5" style={{ color: "#4a6272" }}>{pack.description}</p><ul className="grid gap-2 sm:grid-cols-2">{pack.includes.map((item) => <li key={item} className="flex gap-2 text-sm leading-relaxed" style={{ color: "#16394a" }}><span style={{ color: "#0074a2" }}>✓</span>{item}</li>)}</ul></article>)}</div><p className="mt-6 text-sm leading-relaxed" style={{ color: "#4a6272" }}>Bei Basic ist keine Tiefenreinigung bzw. außergewöhnlich starke Verschmutzung enthalten. Auch Premium gilt bei normaler Verschmutzung; gesonderter Intensiv- oder Tiefenaufwand wird vorher abgestimmt.</p></div></section>

      <section className="py-16" style={{ backgroundColor: "#f4f8fb" }}><div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-16"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] mb-4" style={{ color: "#0074a2" }}>Zusatzleistungen</p><h2 className="text-3xl font-bold tracking-tight mb-4" style={{ color: "#002e40" }}>Für besonderen Aufwand transparent ergänzt</h2><p className="leading-relaxed mb-8" style={{ color: "#4a6272" }}>Zusatzkosten gelten nur für außergewöhnlichen zusätzlichen Aufwand oder eine gesonderte Intensiv-/Tiefenbehandlung – nicht automatisch zusätzlich zu jeder Premium-Leistung.</p><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-8 gap-y-3">{autoaufbereitungExtras.map((extra) => <p key={extra} className="text-sm" style={{ color: "#16394a" }}>+ {extra}</p>)}</div></div></div></section>

      <section className="py-20" style={{ backgroundColor: "#fff" }}><div className="max-w-5xl mx-auto px-6 sm:px-10"><div className="grid gap-12 lg:grid-cols-2"><div><h2 className="text-3xl font-bold tracking-tight mb-5" style={{ color: "#002e40" }}>Was gehört zu einer professionellen Autoaufbereitung?</h2><div className="space-y-5 text-base leading-relaxed" style={{ color: "#4a6272" }}><p>Eine Fahrzeugaufbereitung geht über eine normale schnelle Reinigung hinaus. Innenraum und Außenflächen werden systematisch betrachtet, materialgerecht behandelt und am Ende kontrolliert.</p><p>Bei Leder, Stoff und Alcantara gelten unterschiedliche Anforderungen. Ziel ist ein sauberer, natürlicher OEM-Look – keine speckig glänzenden Oberflächen und keine pauschalen Versprechen bei starken Flecken oder extremem Schmutz.</p><p>Eine professionelle Aufbereitung lohnt sich vor längeren Fahrten, nach Tierhaar- oder Fleckenbelastung, vor einer Leasingrückgabe oder wenn das Fahrzeug wieder gepflegt wirken soll. Eine Wertsteigerung wird dabei nicht versprochen.</p></div></div><div><h2 className="text-3xl font-bold tracking-tight mb-5" style={{ color: "#002e40" }}>Faire und transparente Preise</h2><p className="leading-relaxed" style={{ color: "#4a6272" }}>{autoaufbereitungPricingNote}</p><div className="mt-8 rounded-2xl p-6" style={{ backgroundColor: "#eaf6fa" }}><p className="font-semibold mb-2" style={{ color: "#002e40" }}>Mehr erfahren</p><p className="text-sm leading-relaxed mb-4" style={{ color: "#4a6272" }}>Unser Ratgeber erklärt den Unterschied zwischen Fahrzeugwäsche und Aufbereitung sowie die wichtigsten Materialien.</p><Link href="/ratgeber/autoaufbereitung-was-wird-gemacht" className="text-sm font-semibold" style={{ color: "#0074a2" }}>Zum Ratgeber →</Link></div></div></div></div></section>

      <section className="py-16" style={{ backgroundColor: "#f4f8fb" }}><div className="max-w-4xl mx-auto px-6 sm:px-10"><h2 className="text-3xl font-bold tracking-tight mb-8" style={{ color: "#002e40" }}>Häufige Fragen zur Autoaufbereitung</h2><div className="divide-y" style={{ borderColor: "#d5e8f0" }}>{autoaufbereitungFaqs.map((faq) => <details key={faq.q} className="py-5"><summary className="cursor-pointer font-semibold" style={{ color: "#002e40" }}>{faq.q}</summary><p className="mt-3 leading-relaxed" style={{ color: "#4a6272" }}>{faq.a}</p></details>)}</div></div></section>
      <ContactSection />
    </main><AutoklinikFooter />
  </>;
}
